// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proj4Me.Infra.Data.Context;

namespace Proj4Me.Infra.Data.Migrations
{
    [DbContext(typeof(ProjetoAreaServicoContext))]
    [Migration("20221026232727_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Proj4Me.Domain.Clientes.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IndexClienteProj4Me")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid?>("ProjetoAreaServicoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoAreaServicoId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Proj4Me.Domain.Colaboradores.Colaborador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("IndexColaboradorProj4Me")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Colaborador");
                });

            modelBuilder.Entity("Proj4Me.Domain.Perfis.Perfil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Perfil");
                });

            modelBuilder.Entity("Proj4Me.Domain.ProjetosAreaServicos.ProjetoAreaServico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ColaboradorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<int>("IndexProjetoProj4Me")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<Guid?>("PerfilId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.ToTable("ProjetoAreaServico");
                });

            modelBuilder.Entity("Proj4Me.Domain.ProjetosAreaServicos.ProjetoAreaServicoColaborador", b =>
                {
                    b.Property<Guid>("ColaboradorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjetoAreaServicoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ColaboradorId", "ProjetoAreaServicoId");

                    b.HasIndex("ProjetoAreaServicoId");

                    b.ToTable("ProjetoAreaServicoColaborador");
                });

            modelBuilder.Entity("Proj4Me.Domain.ProjetosAreaServicos.Tarefa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("varchar(5000)");

                    b.Property<DateTime?>("DataEsforco")
                        .IsRequired()
                        .HasColumnType("DateTime");

                    b.Property<int>("IndexProjetoProj4Me")
                        .HasColumnType("int");

                    b.Property<int>("IndexTarefaProj4Me")
                        .HasColumnType("int");

                    b.Property<string>("NomeColaborador")
                        .HasColumnType("varchar(300)");

                    b.Property<string>("NomeTarefa")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<Guid?>("ProjetoAreaServicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TempoGastoDetalhado")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TotalTempoGasto")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoAreaServicoId");

                    b.ToTable("Tarefa");
                });

            modelBuilder.Entity("Proj4Me.Domain.Clientes.Cliente", b =>
                {
                    b.HasOne("Proj4Me.Domain.ProjetosAreaServicos.ProjetoAreaServico", "ProjetoAreaServico")
                        .WithMany("Clientes")
                        .HasForeignKey("ProjetoAreaServicoId");

                    b.Navigation("ProjetoAreaServico");
                });

            modelBuilder.Entity("Proj4Me.Domain.ProjetosAreaServicos.ProjetoAreaServico", b =>
                {
                    b.HasOne("Proj4Me.Domain.Perfis.Perfil", "Perfil")
                        .WithMany("ProjetoAreaServico")
                        .HasForeignKey("PerfilId");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Proj4Me.Domain.ProjetosAreaServicos.ProjetoAreaServicoColaborador", b =>
                {
                    b.HasOne("Proj4Me.Domain.Colaboradores.Colaborador", "Colaborador")
                        .WithMany("ProjetosAreaServicoColaboradores")
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proj4Me.Domain.ProjetosAreaServicos.ProjetoAreaServico", "ProjetoAreaServico")
                        .WithMany("ProjetosAreaServicoColaboradores")
                        .HasForeignKey("ProjetoAreaServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colaborador");

                    b.Navigation("ProjetoAreaServico");
                });

            modelBuilder.Entity("Proj4Me.Domain.ProjetosAreaServicos.Tarefa", b =>
                {
                    b.HasOne("Proj4Me.Domain.ProjetosAreaServicos.ProjetoAreaServico", "ProjetoAreaServico")
                        .WithMany("Tarefas")
                        .HasForeignKey("ProjetoAreaServicoId");

                    b.Navigation("ProjetoAreaServico");
                });

            modelBuilder.Entity("Proj4Me.Domain.Colaboradores.Colaborador", b =>
                {
                    b.Navigation("ProjetosAreaServicoColaboradores");
                });

            modelBuilder.Entity("Proj4Me.Domain.Perfis.Perfil", b =>
                {
                    b.Navigation("ProjetoAreaServico");
                });

            modelBuilder.Entity("Proj4Me.Domain.ProjetosAreaServicos.ProjetoAreaServico", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("ProjetosAreaServicoColaboradores");

                    b.Navigation("Tarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
